#!/usr/bin/env bash
# Sets up nginx server with default configurations and custom response header
sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a\\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i '/server_name _;/a\\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo sed -i '0,/try_files $uri $uri\/ =404;/!b;//i\\t\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo service nginx restart
