#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install haproxy -y

# Define the hostnames of web-01 and web-02 servers
HOSTNAME1=54.173.209.77
HOSTNAME2=54.196.33.13

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF 
frontend http-in
    bind *:80
    default_backend servers

backend myservers
    mode http
    server 105225-web-01 $HOSTNAME1
    server 105225-web-02 $HOSTNAME2
EOF

# Restart HAProxy
sudo service haproxy restart
