#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get update
sudo apt-get install haproxy -y

# Configure loadbalancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend myfrontend
        bind *:80
        default_backend myservers


backend myservers
        balance roundrobin
        server 105225-web-01 54.173.209.77:80 check
        server 105225-web-02 54.196.33.13:80 check
EOT

# start the loadbalancer
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
