#!/usr/bin/env bash
# a script that creates a backup file for a database
# Get the current date in the format we want
DATE=$(date +%d-%m-%Y)

# The name of the archive we'll create
ARCHIVE_NAME="$DATE.tar.gz"

# The name of the dump file
DUMP_NAME="backup.sql"

# The password is the first argument
PASSWORD="$1"

# Dump all databases to the backup file
mysqldump -u root -p"$PASSWORD" --all-databases > "$DUMP_NAME"

# Create the compressed archive
tar -czvf "$ARCHIVE_NAME" "$DUMP_NAME"

echo "MySQL backup completed and saved as $ARCHIVE_NAME"
