#!/usr/bin/env bash
#a script that displays all active IPv4 IPs on the machine it's executed on

# Get the list of all network interfaces
ipv4_addresses=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

# Display the active IPv4 addresses
echo "$ipv4_addresses"
