#!/bin/bash

# Set the name of the private key
KEY_NAME="school"

# Set the number of bits for the key
BITS=4096

# Set the passphrase for the key
PASSPHRASE="betty"

# Create the key pair
ssh-keygen -t rsa -b $BITS -f ~/.ssh/$KEY_NAME -N $PASSPHRASE

echo "RSA key pair created with the name $KEY_NAME in ~/.ssh/"
